# Generated by Django 4.2.28 on 2026-02-08 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Código do Cliente')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo / Razão Social')),
                ('apelido', models.CharField(blank=True, max_length=255, verbose_name='Nome Social / Fantasia')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=30, verbose_name='Telefone/WhatsApp')),
                ('passaporte', models.CharField(blank=True, max_length=50, verbose_name='Passaporte')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('nacionalidade', models.CharField(default='Brasileira', max_length=100, verbose_name='Nacionalidade')),
                ('endereco_origem', models.TextField(blank=True, verbose_name='Endereço no País de Origem')),
                ('endereco_eua', models.TextField(blank=True, verbose_name='Endereço nos EUA')),
                ('saldo_atual', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Saldo Atual (USD)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('doc_entry', models.AutoField(primary_key=True, serialize=False)),
                ('data_fatura', models.DateField(auto_now_add=True, verbose_name='Data da Fatura')),
                ('total_fatura', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total da Fatura (USD)')),
                ('total_pago', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Pago (USD)')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('PARCIAL', 'Pago Parcialmente'), ('PAGO', 'Pago Totalmente'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=15, verbose_name='Status')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faturas', to='gestao.cliente')),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturas',
            },
        ),
        migrations.CreateModel(
            name='TipoVisto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código (ex: O-1, EB-2)')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Visto')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de Visto',
                'verbose_name_plural': 'Tipos de Vistos',
            },
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('TRIAGEM', 'Em Triagem'), ('COLETA', 'Coleta de Documentos'), ('ANALISE', 'Análise Jurídica'), ('USCIS', 'Protocolado no USCIS'), ('RFE', 'Aguardando Evidências (RFE)'), ('APROVADO', 'Aprovado'), ('NEGADO', 'Negado')], default='TRIAGEM', max_length=20, verbose_name='Status')),
                ('num_recibo_uscis', models.CharField(blank=True, max_length=50, verbose_name='Número do Recibo USCIS')),
                ('data_protocolo', models.DateField(blank=True, null=True, verbose_name='Data de Protocolo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos', to='gestao.cliente')),
                ('tipo_visto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestao.tipovisto', verbose_name='Tipo de Visto')),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
            },
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_parcela', models.IntegerField(verbose_name='Nº Parcela')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor da Parcela (USD)')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor Pago (USD)')),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='gestao.fatura')),
            ],
            options={
                'verbose_name': 'Parcela',
                'verbose_name_plural': 'Parcelas',
                'ordering': ['data_vencimento'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField(verbose_name='Data do Pagamento')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total Recebido (USD)')),
                ('metodo', models.CharField(choices=[('ZELLE', 'Zelle'), ('WIRE', 'Wire Transfer'), ('CHECK', 'Check'), ('CASH', 'Cash'), ('CREDIT_CARD', 'Credit Card')], max_length=20, verbose_name='Método')),
                ('referencia', models.CharField(blank=True, max_length=100, verbose_name='Referência/Comprovante')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='gestao.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ModeloContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Modelo')),
                ('conteudo', models.TextField(verbose_name='Conteúdo do Contrato (Markdown/Texto)')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('tipo_visto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao.tipovisto', verbose_name='Tipo de Visto Aplicável')),
            ],
            options={
                'verbose_name': 'Modelo de Contrato',
                'verbose_name_plural': 'Modelos de Contratos',
            },
        ),
        migrations.CreateModel(
            name='LogNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('EMAIL', 'E-mail'), ('WHATSAPP', 'WhatsApp')], max_length=10)),
                ('mensagem', models.TextField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('SUCESSO', 'Sucesso'), ('ERRO', 'Erro')], default='PENDENTE', max_length=10)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='gestao.cliente')),
                ('parcela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao.parcela')),
            ],
        ),
        migrations.AddField(
            model_name='fatura',
            name='processo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faturas', to='gestao.processo'),
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Descrição do Documento')),
                ('arquivo', models.FileField(upload_to='documentos/processos/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('validade', models.DateField(blank=True, null=True, verbose_name='Data de Validade')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='gestao.processo')),
            ],
        ),
        migrations.CreateModel(
            name='AlocacaoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_alocado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Alocado (USD)')),
                ('pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='gestao.pagamento')),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='gestao.parcela')),
            ],
        ),
    ]
