# Generated by Django 4.2.28 on 2026-02-08 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapaProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('concluida', models.BooleanField(default=False, verbose_name='Concluída')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='gestao.processo')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Etapa do Processo',
                'verbose_name_plural': 'Checklist do Processo',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='EtapaPadrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=1, verbose_name='Ordem')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título da Etapa')),
                ('descricao', models.TextField(blank=True, verbose_name='O que deve ser feito?')),
                ('obrigatoria', models.BooleanField(default=True)),
                ('tipo_visto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas_padrao', to='gestao.tipovisto')),
            ],
            options={
                'verbose_name': 'Etapa Padrão (Template)',
                'verbose_name_plural': 'Etapas Padrão (Templates)',
                'ordering': ['tipo_visto', 'ordem'],
            },
        ),
    ]
