# Generated by Django 4.2.28 on 2026-02-08 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_etapaprocesso_etapapadrao'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='etapa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arquivos', to='gestao.etapaprocesso', verbose_name='Etapa Correspondente'),
        ),
    ]
