# Generated by Django 4.2.28 on 2026-02-08 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0003_documento_etapa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('ALUGUEL', 'Aluguel / Office'), ('SALARIO', 'Salários / Freelancers'), ('MARKETING', 'Marketing / Ads'), ('SOFTWARE', 'Software / Assinaturas'), ('TAXA', 'Taxas Governamentais Pagas'), ('OUTROS', 'Outros')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_vencimento', models.DateField()),
                ('pago', models.BooleanField(default=False)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='comprovantes/despesas/')),
            ],
            options={
                'verbose_name': 'Contas a Pagar',
                'verbose_name_plural': 'Contas a Pagar',
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='comentarios',
            field=models.TextField(blank=True, verbose_name='Feedback / Observações'),
        ),
        migrations.AddField(
            model_name='documento',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Aguardando Envio'), ('REVISAO', 'Sob Revisão'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado / Pendente de Correção')], default='PENDENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='tipovisto',
            name='taxa_uscis_padrao',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Taxa USCIS Padrão (USD)'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='documentos/processos/'),
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('status', models.CharField(choices=[('NOVO', 'Novo Contato'), ('QUALIFICADO', 'Qualificado (Interessado)'), ('PROPOSTA', 'Proposta Enviada'), ('CONVERTIDO', 'Convertido em Cliente'), ('PERDIDO', 'Perdido')], default='NOVO', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('interesse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao.tipovisto')),
            ],
        ),
    ]
