# Generated by Django 4.2.28 on 2026-02-08 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestao', '0006_historicallognotificacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total (USD)')),
                ('entrada', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor de Entrada (USD)')),
                ('num_parcelas', models.PositiveIntegerField(default=1, verbose_name='Número de Parcelas')),
                ('frequencia', models.CharField(choices=[('SEMANAL', 'Semanal'), ('QUINZENAL', 'Quinzenal'), ('MENSAL', 'Mensal')], default='MENSAL', max_length=20, verbose_name='Frequência')),
                ('data_proposta', models.DateField(auto_now_add=True, verbose_name='Data da Proposta')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ENVIADO', 'Enviado ao Cliente'), ('ACEITO', 'Aceito (Gerar Fatura)'), ('REJEITADO', 'Rejeitado')], default='RASCUNHO', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos', to='gestao.cliente')),
                ('tipo_visto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestao.tipovisto')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
            },
        ),
        migrations.CreateModel(
            name='OrcamentoParcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_parcela', models.PositiveIntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_vencimento', models.DateField()),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas_preview', to='gestao.orcamento')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalOrcamento',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total (USD)')),
                ('entrada', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor de Entrada (USD)')),
                ('num_parcelas', models.PositiveIntegerField(default=1, verbose_name='Número de Parcelas')),
                ('frequencia', models.CharField(choices=[('SEMANAL', 'Semanal'), ('QUINZENAL', 'Quinzenal'), ('MENSAL', 'Mensal')], default='MENSAL', max_length=20, verbose_name='Frequência')),
                ('data_proposta', models.DateField(blank=True, editable=False, verbose_name='Data da Proposta')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ENVIADO', 'Enviado ao Cliente'), ('ACEITO', 'Aceito (Gerar Fatura)'), ('REJEITADO', 'Rejeitado')], default='RASCUNHO', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cliente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gestao.cliente')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tipo_visto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gestao.tipovisto')),
            ],
            options={
                'verbose_name': 'historical Orçamento',
                'verbose_name_plural': 'historical Orçamentos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
