# Generated by Django 4.2.28 on 2026-02-09 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0007_orcamento_orcamentoparcela_historicalorcamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprocesso',
            name='orcamento',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Orçamento aprovado que originou este processo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gestao.orcamento', verbose_name='Orçamento Vinculado'),
        ),
        migrations.AddField(
            model_name='processo',
            name='orcamento',
            field=models.ForeignKey(blank=True, help_text='Orçamento aprovado que originou este processo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao.orcamento', verbose_name='Orçamento Vinculado'),
        ),
    ]
