# Generated by Django 4.2.28 on 2026-02-09 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0008_historicalprocesso_orcamento_processo_orcamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelocontrato',
            name='tipo_visto',
        ),
        migrations.AddField(
            model_name='modelocontrato',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='modelocontrato',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='modelocontrato',
            name='conteudo',
            field=models.TextField(help_text='Use variáveis como {{cliente_nome}}, {{tipo_visto}}, {{valor_total}}, etc.', verbose_name='Conteúdo do Contrato (HTML)'),
        ),
        migrations.AlterField(
            model_name='modelocontrato',
            name='nome',
            field=models.CharField(default='Contrato Padrão G IMIGRA', max_length=100, verbose_name='Nome do Modelo'),
        ),
    ]
