# Generated by Django 4.2.28 on 2026-09-16 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestao', '0009_remove_modelocontrato_tipo_visto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAnexoCliente',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título / Descrição')),
                ('categoria', models.CharField(choices=[('FOTO', 'Foto / Imagem'), ('PASSAPORTE', 'Passaporte / Documento de Identidade'), ('COMPROVANTE', 'Comprovante de Residência'), ('CERTIDAO', 'Certidão (Nascimento, Casamento, etc.)'), ('FINANCEIRO', 'Comprovante Financeiro / Extrato'), ('FORMULARIO', 'Formulários / Petições Assinadas'), ('DOCUMENTO', 'Outros Documentos / Arquivos')], default='DOCUMENTO', max_length=50, verbose_name='Tipo / Categoria')),
                ('arquivo', models.TextField(max_length=100, verbose_name='Arquivo / Foto')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_upload', models.DateTimeField(blank=True, editable=False, verbose_name='Data do Upload')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cliente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gestao.cliente', verbose_name='Cliente')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Anexo do Cliente',
                'verbose_name_plural': 'historical Anexos do Cliente',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='AnexoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título / Descrição')),
                ('categoria', models.CharField(choices=[('FOTO', 'Foto / Imagem'), ('PASSAPORTE', 'Passaporte / Documento de Identidade'), ('COMPROVANTE', 'Comprovante de Residência'), ('CERTIDAO', 'Certidão (Nascimento, Casamento, etc.)'), ('FINANCEIRO', 'Comprovante Financeiro / Extrato'), ('FORMULARIO', 'Formulários / Petições Assinadas'), ('DOCUMENTO', 'Outros Documentos / Arquivos')], default='DOCUMENTO', max_length=50, verbose_name='Tipo / Categoria')),
                ('arquivo', models.FileField(upload_to='clientes/anexos/%Y/%m/', verbose_name='Arquivo / Foto')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data do Upload')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='gestao.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Anexo do Cliente',
                'verbose_name_plural': 'Anexos do Cliente',
                'ordering': ['-data_upload'],
            },
        ),
    ]
